#!/usr/bin/env python3
"""
Parse a ClubSpark courses CSV into display-ready JSON for the adults and
juniors newsletter blocks. This is the only place course data is derived —
the newsletter HTML itself is written directly (see SKILL.md's HTML rules),
not generated by a script.

Usage:
    python3 parse_courses.py <path-to-csv>

Output JSON:
{
  "adults": [
    {
      "skill_level": "Beginner",
      "day": "Saturday",
      "time": "9am",                       # 12h, formatted
      "venue": "Belair Park",
      "duration": "6 weeks",
      "start_date": "5 Sep",               # short display date
      "start_date_iso": "2026-09-05T00:00:00.000Z",  # for booking button URLs
      "participants": 5,
      "spots_flag": null                   # null | "limited" (7-9) | "full" (10+)
    }
  ],
  "juniors": [
    {
      "colour": "Blue",                    # Blue | Red | Orange | Green | null
      "day": "Saturday",
      "time": "8:45am",
      "venue": "Dulwich Park",
      "duration": "8 weeks",
      "start_date": "5 Sep",
      "participants": 3,
      "spots_flag": null
    }
  ]
}
"""
import json
import sys
from datetime import datetime
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))

from csv_processor import CSVProcessor  # noqa: E402

JUNIOR_COLOURS = {"Blue", "Red", "Orange", "Green"}


def format_time(time_str: str) -> str:
    """24h -> 12h, matching the original html_generator._format_time exactly."""
    try:
        if ":" not in time_str:
            return time_str
        hour_s, minute_s = time_str.split(":")
        hour, minute = int(hour_s), int(minute_s)
        minute_part = f":{minute:02d}" if minute != 0 else ""
        if hour > 12:
            return f"{hour - 12}{minute_part}pm"
        elif hour == 12:
            return f"12{minute_part}pm"
        elif hour == 0:
            return f"12{minute_part}am"
        else:
            return f"{hour}{minute_part}am"
    except Exception:
        return time_str


def format_short_date(formatted_start_date: str) -> str:
    """'05 Sep 2026' -> '5 Sep', matching _format_short_date exactly."""
    try:
        parts = formatted_start_date.split(" ")
        if len(parts) == 3:
            day, month, _year = parts
            return f"{int(day)} {month}"
        return formatted_start_date
    except Exception:
        return formatted_start_date


def to_iso_date(start_date: str) -> str:
    """Matches _extract_earliest_date's per-row date parsing, ISO-formatted."""
    try:
        s = str(start_date)
        if "/" in s:
            date_obj = datetime.strptime(s, "%d/%m/%Y")
        else:
            date_obj = datetime.strptime(s, "%Y-%m-%d")
        return date_obj.strftime("%Y-%m-%dT00:00:00.000Z")
    except Exception:
        return ""


def spots_flag(participants: int) -> str | None:
    if participants >= 10:
        return "full"
    if participants >= 7:
        return "limited"
    return None


def extract_junior_colour(name: str) -> str | None:
    first_word = name.strip().split(" ")[0].capitalize()
    return first_word if first_word in JUNIOR_COLOURS else None


def main() -> None:
    if len(sys.argv) < 2:
        raise SystemExit("Usage: parse_courses.py <path-to-csv>")

    with open(sys.argv[1], "rb") as f:
        df = CSVProcessor().process_csv(f)

    adults = []
    for _, row in df[df["Type"].str.lower() == "adult"].iterrows():
        participants = int(row.get("Active Participants", 0))
        adults.append(
            {
                "skill_level": row.get("Skill Level", "Unknown"),
                "day": row.get("Day", ""),
                "time": format_time(str(row.get("Time", ""))),
                "venue": row.get("Venue", "Unknown Venue"),
                "duration": row.get("Duration Text", ""),
                "start_date": format_short_date(row.get("Formatted Start Date", "")),
                "start_date_iso": to_iso_date(row.get("Start Date", "")),
                "participants": participants,
                "spots_flag": spots_flag(participants),
            }
        )

    juniors = []
    for _, row in df[df["Type"].str.lower() == "junior"].iterrows():
        participants = int(row.get("Active Participants", 0))
        juniors.append(
            {
                "colour": extract_junior_colour(str(row.get("Name", ""))),
                "day": row.get("Day", ""),
                "time": format_time(str(row.get("Time", ""))),
                "venue": row.get("Venue", ""),
                "duration": row.get("Duration Text", ""),
                "start_date": format_short_date(row.get("Formatted Start Date", "")),
                "participants": participants,
                "spots_flag": spots_flag(participants),
            }
        )

    json.dump({"adults": adults, "juniors": juniors}, sys.stdout, indent=2)
    sys.stdout.write("\n")


if __name__ == "__main__":
    main()
